### ISSUE TITLE
Model not found

### ISSUE THREAD

**Issue by qzqzzw** [yohanjo/tacl_arg_rel#1]
Hello professor. I ran into a problem when I ran the code:
`$ python main_sup_blend.py -task logbert -dataset kialo -dtype normative -logic nli senti causal normarg -cuda 0`
`error:Model not found`
![image](https://user-images.githubusercontent.com/57550503/126579734-32143622-4cfd-4cfd-bb51-e000ae159660.png)
I hope you can help me solve this problem, thank you

**Comment by yohanjo** [comment]
Thanks for reporting this isseu.
We'll look into it and get back to you.

Best,
Yohan Jo

**Comment by BabaVegato** [comment]
Hello, 
Did you solve the issue ? I also have the same issue, and don't know what to do..
Thanks a lot for the repo anyway !

**Comment by yohanjo** [comment]
Hello,

Sorry for the inconvenience. The error indicates missing pretrained models.
I've uploaded all pretrained models to a repository and added instructions in the README in the `src` folder.
Please follow the instructions under `LogBERT > Run > To run LogBERT`.
Let me know if you run into any other issues.
