### ISSUE TITLE
Could not find the result file.

### ISSUE THREAD

**Issue by benjpau** [yohanjo/tacl_arg_rel#3]
I ran this command:
python main_psl.py -dataset kialo -dtype causal
to reproduce the results in "Table 5(a): Non-normative Arguments" of your paper.

However, after running, I found the following result in "data_test/output/log.txt":

> psl-jar file found cached, skipping download.
> Running PSL Inference
> 0    [main] INFO  org.linqs.psl.cli.Launcher  - Running PSL CLI Version 2.2.2-5f9a472
> 654  [main] INFO  org.linqs.psl.cli.Launcher  - Loading data
> 33360 [main] INFO  org.linqs.psl.cli.Launcher  - Data loading complete
> 33361 [main] INFO  org.linqs.psl.cli.Launcher  - Loading model from kialo_causal_pairs-learned.psl
> 33438 [main] INFO  org.linqs.psl.cli.Launcher  - Model loading complete
> 33438 [main] INFO  org.linqs.psl.cli.Launcher  - Starting inference with class: org.linqs.psl.application.inference.MPEInference
> 90791 [main] INFO  org.linqs.psl.application.inference.MPEInference  - Grounding out model.
> 96834 [main] INFO  org.linqs.psl.application.inference.MPEInference  - Grounding complete.
> 99090 [main] INFO  org.linqs.psl.application.inference.InferenceApplication  - Beginning inference.
> 100913 [main] INFO  org.linqs.psl.reasoner.admm.ADMMReasoner  - Optimization completed in 58 iterations. Objective: 14776.424, Feasible: true, Primal res.: 0.09559699, Dual res.: 0.2679048
> 100962 [main] INFO  org.linqs.psl.application.inference.InferenceApplication  - Inference complete.
> 100962 [main] INFO  org.linqs.psl.application.inference.InferenceApplication  - Writing results to Database.
> 158134 [main] INFO  org.linqs.psl.application.inference.InferenceApplication  - Results committed to database.
> 158134 [main] INFO  org.linqs.psl.cli.Launcher  - Inference Complete
> 159253 [main] INFO  org.linqs.psl.cli.Launcher  - Starting evaluation with class: org.linqs.psl.evaluation.statistics.DiscreteEvaluator.
> 167184 [main] INFO  org.linqs.psl.cli.Launcher  - Evaluation results for RELATION -- Accuracy: 0.721624, F1: 0.533724, Positive Class Precision: 0.604210, Positive Class Recall: 0.477966, Negative Class Precision: 0.763672, Negative Class Recall: 0.843453
> 167184 [main] INFO  org.linqs.psl.cli.Launcher  - Evaluation complete.

In the second last line, I can only see the results for POSITIVE and NEGATIVE, and i did find the results for NEUTRAL.
So, do I have to calculate it myself from "data_test/output/RELATION.txt" to get the results in your paper(i.e. ACC AUC F1 F1_sup F1_att F1_neu) ?

Looking forward to your reply.
Thanks!

**Comment by yohanjo** [comment]
Hello,

Yes, I used the results in RELATION.txt to calculate the evaluation metrics
(macro-average). I figured that the basic output metrics of PSL were not
very helpful.
Do you have all of sup, att, and neu in `RELATION.txt`?

Best,
Yohan Jo

**Comment by benjpau** [comment]
Yes, I get it now.
Thanks for your reply!
